version: '3.9'

services:
  postgres:
    image: postgres:14.1-alpine
    container_name: Postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    expose:
      # Opens port 3306 on the container
      - '5432'
    volumes:
      - ./apps/postgres:/var/lib/postgresql/data
