version: '2.2'

services:
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - ./mongodb:/storage/mongodb
  postgres:
      image: postgres:14.1-alpine
      container_name: Postgres
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      ports:
        - '5432:5432'
      volumes:
        - ./postgres:/storage/postgres